# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Laconic Labs
site_url: https://laconic-labs.dev
site_description: Unlock the power of AI with Laconic Labs
site_author: Mike Schulte
# repo_url: https://github.com/squidfunk/mkdocs-material

theme: 
  name: material
  logo: img/robot-assistant.png
  favicon: img/robot-assistant.png
  palette: 
    - scheme: default
      primary: custom
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: custom
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate

plugins:
  - blog:
      archive: false
      blog_toc: true
      post_dir: blog/posts
      authors_file: "{blog}/authors.yml"

nav:
  - Welcome: 'index.md'
  - Services: 'services/services.md'
  - Blog:
    - 'blog/index.md'
  - Walk-Throughs:
    - Overview: 'walk-throughs/walk-throughs.md'


extra_css:
  - styles.css

extra:
  analytics:
    provider: google
    property: G-V73R2SYPPY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
